net: ethernet: phytium: add a missing declaration for *np
Fix a compilation error:

drivers/net/ethernet/phytium/phytmac_platform.c: In function ‘phytmac_plat_probe’:
drivers/net/ethernet/phytium/phytmac_platform.c:98:55: error: ‘np’ undeclared (first use in this function); did you mean ‘up’?
   98 |                 match = of_match_node(phytmac_dt_ids, np);
      |                                                       ^~
      |                                                       up

Signed-off-by: Mingcong Bai <baimingcong@uniontech.com>
Ref: https://github.com/deepin-community/kernel-rolling/commit/eec8d65bd08c528c7909a78e1a25b0cbcff9cadc