AOSCOS: PCI: sg2042: fix dependency for PCIE_SG2042
Mark PSI_MSI as a dependency, not as a select to avoid a recursive
dependency error on our amd64 configuration:

  error: recursive dependency detected:
	  symbol OF is selected by X86_INTEL_CE
	  symbol X86_INTEL_CE depends on X86_IO_APIC
	  symbol X86_IO_APIC depends on X86_UP_APIC
	  symbol X86_UP_APIC prompt is visible depending on PCI_MSI
	  symbol PCI_MSI is selected by PCIE_SG2042
	  symbol PCIE_SG2042 depends on OF

Revise the "select" as "depends on" to workaround this issue.

Suggested-by: Han Gao <rabenda.cn@gmail.com>
Signed-off-by: Mingcong Bai <jeffbai@aosc.io>