HACK: rust: pin-init: Disable references to previously initialized fields
aop_audio uses pin-init on `#[repr(C, packed)]` embedded into other
structs. This fails with "error[E0793]: reference to packed field is
unaligned" since packed struct have an alingment of 1 byte.

Fixes: 42415d163e5d ("rust: pin-init: add references to previously initialized fields")